### ISSUE TITLE
This is really slow (@alexlur’s repository is way faster with the same features)

### ISSUE THREAD

**Issue by chris-morgan** [ezolenko/rollup-plugin-typescript2#10]
A simple, unscientific test of putting TypeScript into an existing Rollup project (15KLOC, 30 including comments and blanks):

- No TypeScript: 1.4 seconds;
- `@alexlur/rollup-plugin-typescript` 1.0.4: 5.1 seconds;
- `rollup-plugin-typescript2` 0.3.0 (this repository): roughly 16 seconds, or 6.5 if it has already been built.

And I have another that I plan to port which is thrice the size—but getting toward a minute would be hard to stomach for trivial changes.

If I insert a simple TypeScript error in one of the files:

- @alexlur/rollup-plugin-typescript: it produces the errors to stderr after about 0.8 seconds:

  ```
  /mnt/c/fastmail/overture/source/Overture/core/Core.js(171,16): error TS8010: 'types' can only be used in a .ts file.
  🚨   There were TypeScript errors transpiling
  source/Overture/core/Core.js
  ```

- rollup-plugin-typescript2: it produces much the same output (though slightly differently formatted—notably lacking the error codes) to stderr after about 3.4 seconds:

  ```
  🚨   rpt2: /mnt/c/fastmail/overture/source/Overture/core/Core.js (171,16): 'types' can only be used in a .ts file.
  source/Overture/core/Core.js
  ```

At this stage I can’t see any reason why I should use this plugin rather than @alexlur’s. Performance is a *major* feature.

**Comment by ezolenko** [comment]
Yeah, that's the price you pay for error checking. 

Unless there were changes in the original plugin (or in typescript itself) since I started this one (can't check right now) it wouldn't show a whole class of semantic errors that are not immediately fatal. For example incorrectly implemented interfaces and many other type errors that don't affect transpiling and that require typescript to read more files (any imports and all ambient types) in addition to the one currently being transpiled. Start a moderate refactoring and abandon it in the middle, then see how many errors are not showing up.

Checking semantic errors prevents treating every file independently.

This plugin has a few issues with dependency detection as well, but those would hopefully be fixed eventually. The goal is to get exactly the same errors out of rollup as you'd get by running tsc directly in both clean build and running from cache. 

Secondary goal is to get clean build times to be comparable to tsc build times (plus rollup work).
