### ISSUE TITLE
semantic error TS2339 Property 'includes' does not exist on type 'string[]'.

### ISSUE THREAD

**Issue by mesqueeb** [ezolenko/rollup-plugin-typescript2#115]
#### What happens and why it is wrong

Hey I'm new to TypeScript, and trying to compile my first .ts file with auto-type declarations based on what I wrote in the functions.

Error: `semantic error TS2339 Property 'includes' does not exist on type 'string[]'.`

Sorry if I'm stupid! ><

#### Environment 

Tokyo

#### Versions

    "rollup": "^0.65.2",
    "rollup-plugin-typescript2": "^0.17.0",
    "tslib": "^1.9.3",
    "typescript": "^3.0.3"

#### rollup.config.js

`typescript()` is the only plugin

#### tsconfig.json

```
{
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "./types/"
  },
}
```

#### plugin output with verbosity 3

```
loaded build/rollup.js with warnings
(!) Unused external imports
default imported from external module 'rollup-plugin-babel' but never used

src/index.ts → dist/index.cjs.js...
rpt2: typescript version: 3.0.3
rpt2: tslib version: 1.9.3
rpt2: rollup-plugin-typescript2 version: 0.17.0
rpt2: plugin options:
{
    "verbosity": 3,
    "check": true,
    "clean": false,
    "cacheRoot": "/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/.rpt2_cache",
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)"
    ],
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "typescript": "version 3.0.3",
    "useTsconfigDeclarationDir": false,
    "tsconfigOverride": {},
    "transformers": [],
    "tsconfigDefaults": {},
    "objectHashIgnoreUnknownHack": false
}
rpt2: rollup config:
{
    "experimentalCacheExpiry": 10,
    "external": [
        "is-what",
        "",
        ""
    ],
    "inlineDynamicImports": false,
    "input": "src/index.ts",
    "chunkGroupingSize": 5000,
    "perf": false,
    "plugins": [
        {
            "name": "rpt2"
        }
    ],
    "entry": "src/index.ts"
}
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/.rpt2_cache/placeholder",
    "moduleResolution": 2,
    "declarationDir": null,
    "sourceRoot": null
}
rpt2: parsed tsconfig: {
    "options": {
        "module": 5,
        "noEmitHelpers": false,
        "importHelpers": true,
        "noResolve": false,
        "noEmit": false,
        "inlineSourceMap": false,
        "outDir": "/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/.rpt2_cache/placeholder",
        "moduleResolution": 2,
        "declarationDir": null,
        "sourceRoot": null
    },
    "fileNames": [
        "/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/play.ts",
        "/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/src/index.ts",
        "/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/src/tsplay.ts"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "compilerOptions": {
            "module": "ES2015"
        },
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {
        "/users/lucaban/.ghq/github.com/mesqueeb/merge-anything": 1
    },
    "compileOnSave": false,
    "configFileSpecs": {
        "includeSpecs": [
            "**/*"
        ],
        "validatedIncludeSpecs": [
            "**/*"
        ],
        "wildcardDirectories": {
            "/users/lucaban/.ghq/github.com/mesqueeb/merge-anything": 1
        }
    }
}
rpt2: included:
'[
    "*.ts+(|x)",
    "**/*.ts+(|x)"
]'
rpt2: excluded:
'[
    "*.d.ts",
    "**/*.d.ts"
]'
rpt2: Ambient types:
rpt2:     /Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/node_modules/@types/estree/index.d.ts
rpt2:     /Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/node_modules/@types/node/index.d.ts
rpt2: ambient types changed, redoing all semantic diagnostics
rpt2: transpiling '/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/src/index.ts'
rpt2:     cache: '/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/.rpt2_cache/rpt2_981babe4c594e7b1738a012b65f2d126f121c6aa/code/cache/eac68a0bd5863676000379465d96fa8b9b471848'
rpt2:     cache miss
rpt2:     cache: '/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/.rpt2_cache/rpt2_981babe4c594e7b1738a012b65f2d126f121c6aa/syntacticDiagnostics/cache/eac68a0bd5863676000379465d96fa8b9b471848'
rpt2:     cache miss
rpt2:     cache: '/Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/.rpt2_cache/rpt2_981babe4c594e7b1738a012b65f2d126f121c6aa/semanticDiagnostics/cache/eac68a0bd5863676000379465d96fa8b9b471848'
rpt2:     cache miss
[!] (rpt2 plugin) Error: /Users/lucaban/.ghq/github.com/mesqueeb/merge-anything/src/index.ts(19,36): semantic error TS2339 Property 'includes' does not exist on type 'string[]'.
```

**Comment by ezolenko** [comment]
You need to set `target: "es2016"` in your tsconfig -- `Array.prototype.includes` doesn't exist in es2015 version of java script (which is the default this plugin sets if target is empty).

That will make typescript produce es2016 code though -- if you can't use that, you will have to use babel do downconvert to what you can use.

**Comment by mesqueeb** [comment]
@ezolenko but i want to target es2015. ; )
I foxed it by adding `//@ts-ignore` above that line.

**Comment by ezolenko** [comment]
Eh, but `includes()` is not in es2015, so your resulting js code is not es2015 and if you deploy on a host that only support es2015, this will throw an error :)

**Comment by mesqueeb** [comment]
@ezolenko exactly! Doesn’t TS change my code to es5 just like Babel if I set target to es2015?

**Comment by agilgur5** [comment]
Pretty old issue, but figured I'd answer the above question.

> Doesn’t TS change my code to es5 just like Babel if I set target to es2015?

Both TS and Babel transpile _syntax_ down, yes, but they can't supplant non-existent functionality in the old language spec. This isn't a syntax transform, `Array.includes` just doesn't exist in ES2015.

What you would need is to _polyfill_ that functionality if you want to use it. Polyfills solve this issue, not syntax transforms. Different problems.

For what it's worth, it is a relatively common misconception that transpilers do polyfilling too, especially in a simple case like `Array.includes` that could be re-written in one line of ES2015 code with `indexOf`. But they just typically don't perform that kind of transformation unless you use a plugin.

`@babel/preset-env` does support automatically polyfilling via its [`useBuiltIns` option](https://babeljs.io/docs/en/babel-preset-env#usebuiltins), which existed back in 2018 too IIRC.
But if you're building a library, you'd probably want to use the more recent [`babel-polyfills`](https://github.com/babel/babel-polyfills) directly instead with `method: 'usage-pure'` in order to not pollute downstream consumers' environments (instead of `preset-env`'s `useBuiltIns`, which doesn't have a pure option yet afaik, but it uses `babel-polyfills` under-the-hood nowadays).
I've contributed a bit there and recently did a TS rewrite of the codebase, so can confirm that it's a good tool 😉

I don't know if there's any TS-specific tooling for auto-polyfilling, that being said. My Rollup config often has a 2-step process, from rpt2 for TS + type-checking + declarations to `esnext` (or similar), then `@rollup/plugin-babel` for Babel to transpile down to whatever my `browserslistrc` says and auto-polyfill if necessary.
