### ISSUE TITLE
Error: Unexpected character '@'

### ISSUE THREAD

**Issue by viT-1** [ezolenko/rollup-plugin-typescript2#164]
#### What happens and why it is wrong

Just try [same way](https://github.com/ezolenko/rollup-plugin-typescript2/issues/159#issuecomment-507354473)
index.ts:
`import SomeComponent from '@common/SomeComponent';`
and got error: 

> Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
>     at error (C:\Projects\PACWorld\Branches\PacWorldWeb3-vuejs\PacWorld3\node_modules\rollup\dist\rollup.js:9408:30)
>     at Module.error (C:\Projects\PACWorld\Branches\PacWorldWeb3-vuejs\PacWorld3\node_modules\rollup\dist\rollup.js:13347:9)
>     at tryParse (C:\Projects\PACWorld\Branches\PacWorldWeb3-vuejs\PacWorld3\node_modules\rollup\dist\rollup.js:13262:16)
>     at Module.setSource (C:\Projects\PACWorld\Branches\PacWorldWeb3-vuejs\PacWorld3\node_modules\rollup\dist\rollup.js:13573:33)
>     at Promise.resolve.catch.then.then.then (C:\Projects\PACWorld\Branches\PacWorldWeb3-vuejs\PacWorld3\node_modules\rollup\dist\rollup.js:16398:20)

#### Environment 
Win10, MS Visual Studio 2019

#### Versions
- typescript: 3.5.2
- rollup: 1.17.0
- rollup-plugin-typescript2: 0.22.1

#### rollup.config.js
```
const rolTts = require('ttypescript');
const rolTypescript = require('rollup-plugin-typescript2');
...
plugins: [
	rolTypescript({
		tsconfig: './src/tsconfig.json',
		clean: true,
		tsconfigOverride: {
			declaration: false,
			compileOnSave: false,
		},
		typescript: rolTts,
	}),
]
```

#### tsconfig.json
```
	"extends": "../tsproject.json",
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"@common/*": ["./common.blocks/*"]
		}
	}
```

**Comment by viT-1** [comment]
Initially tsconfig was without "compileOnSave" option,
but I have two funny errors:

> rpt2: config error TS5023: Unknown compiler option 'compileOnSave'.
> rpt2: config error TS5024: Compiler option 'compileOnSave' requires a value of type boolean.

**Comment by ezolenko** [comment]
You need a `rollup-plugin-node-resolve` plugin in front of typescript plugin

**Comment by viT-1** [comment]
Now I haven't  TS5023 & TS5024 errors but still have problems with '@'

**Comment by viT-1** [comment]
Please reopen the issue.
I try your rollup-plugin with @zerollup/ts-transform-paths transformer configured two ways: 

1. through tsconfig.json >compilerOptions>plugins
2. through transformers options

and still haven't success!
but [have success](https://github.com/viT-1/systemjs-ts-es6-vue) with npm run ttsc (ttypescript) which use only tsconfig.json with @zerollup/ts-transform-paths

**Comment by ezolenko** [comment]
You can probably use `transformers` option on rpt2 plugin itself if you want to avoid ttypescript wrapper. Might have to shim the interfaces a bit to make `@zerollup/ts-transform-paths` work (or maybe not, let me know either way if you go this route).

**Comment by ezolenko** [comment]
If `ts-transform-paths` is there anything to fix on this side though?

**Comment by viT-1** [comment]
I tried transformers ([point 2](#issuecomment-523846771)), no success =(

**Comment by viT-1** [comment]
Migrate to rollup-plugin-typescript with rollup-plugin-import-resolver

**Comment by agilgur5** [comment]
I'm not sure what was going on in OP's codebase as no repro was provided and the issue they linked to (#159) was due to an invalid misconfiguration. The config posted here has a similar misconfiguration, `compilerOptions` is missing within `tsconfigOverrides`.

I also found the [old commit](https://github.com/viT-1/systemjs-ts-es6-vue/tree/ccd20fe6fd27892927ef200ad65fc4d3d25b76ba) from a repo they later linked (I modified their comment to point to the permalink as well), but didn't see a Rollup config there, so hard to tell what the issue was here.

It was likely a misconfiguration though, as lots of people have gotten path aliases, `ttypescript`, and `ts-transform-paths` working with this plugin; see #201 for one reference (can point to more in downstream TSDX as well).
OP also said in their last comment that they eventually used `rollup-plugin-import-resolver`, which is a plugin for resolving things like path aliases.
