### ISSUE TITLE
Monorepo: watch mode results in `Error: Could not find source file`

### ISSUE THREAD

**Issue by jrburke** [ezolenko/rollup-plugin-typescript2#214]
#### What happens and why it is wrong

A normal one-time build works fine. However, when using `rollup -w`, rpt2 seems to have trouble finding source files if I edit one of the deeper module dependencies in one of the other packages.

This is with a Lerna monorepo setting up symlinks to the in-repo dependencies.

Test repo: https://github.com/jrburke/jr-monorepo-rpt2

I do not want to use `preserveSymlinks` because in my real project, it results in duplicates of modules in the final built project, since multiple packages in the repo share common dependencies. I have tried a version using `preserveSymlinks`, and so as a last resort I could configure a dev setup that uses `preserveSymlinks`, but standalone/first time builds work without it, and I would like to keep the watch setup the same as the normal builds.

#### Environment 

Details to reproduce in the above example repo.

#### Versions
- typescript: 3.8.3
- rollup: 1.32.1
- rollup-plugin-typescript2: 0.26.0

#### rollup.config.js

```js
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import typescript from 'rollup-plugin-typescript2';

export default {
  input: 'src/index.ts',
  output: {
    file: 'dist/jr-player.js',
    format: 'iife',
    name: 'jrPlayer',
    exports: 'named'
  },
  watch: {
    include: ['src/**', '../jr-lib/src/**', '../jr-auth/src/**']
  },
  plugins: [
    typescript({
      include: ['src/**/*.ts+(|x)', '../jr-lib/**/*.ts+(|x)', '../jr-auth/**/*.ts+(|x)'],
      verbosity: 3
    }),
    resolve(),
    commonjs()
  ]
};
```

#### tsconfig.json

Top level tsconfig.json:

```json5
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "es2015",
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom"
    ],
    "strict": true,
    "sourceMap": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": false,
    "esModuleInterop": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": true
  }
}
```

`packages/jr-player/tsconfig.json`:

```json5
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "target": "es5",
    "declarationDir": "lib",
    "outDir": "lib"
  },
  "include": ["."]
}
```

#### package.json

I don't think it is relevant, but it is in the test repo.

#### plugin output with verbosity 3

Attached, but also in test repo at `verbose-error.txt`:

[verbose-error.txt](https://github.com/ezolenko/rollup-plugin-typescript2/files/4316015/verbose-error.txt)

**Comment by ezolenko** [comment]
Might be related to #188

Another workaround is to disable typechecking with `check: false`, of course that removes majority of functionality...

**Comment by rmedaer** [comment]
I have the issue combining `rollup-plugin-typescript2` and `rollup-plugin-postcss`. When I import a _css_ file (e.g. `import * as style from ./mystyle.css`) and I enable _watch_ flag, it gives me the same error.

I'll try debug a little bit more, but indeed `check: false` fix the issue.

**Comment by daief** [comment]
> I have a similar issue currently, using lerna and a `(plugin rpt2) Error: Could not find source file` showed up.
> 
> I fix this by simply change the order of the plugins from:
> 
> ```
> [
>   typescript(),
>   resolve(),
>   commonjs(),
> ]
> ```
> 
> to
> 
> ```
> [
>   resolve(),
>   commonjs(),
>   typescript(),
> ]
> ```
> 
> Maybe you can have a shot.

This solved my same problem. 

绝了。

**Comment by toakleaf** [comment]
Reordering didn't help me much.  Had to go with the `check: false` method to get hot reloading working again.

For more context, I'm using turborepo monorepo, and while the initial running of the dev server finds my typescript files in the monorepo packages/ dir, all subsequent hot reloads fail to find the dependencies.

**Comment by yuuk** [comment]
It's occasionally occur the error in my case, when i modify `rollup.config.js` and save, it compiled successfully.

**Comment by agilgur5** [comment]
This seems to have been fixed by #332 which was released in [`0.32.0`](https://github.com/ezolenko/rollup-plugin-typescript2/releases/0.32.0).

I tested the reproduction with `0.31`, which had the same error, then upgraded to `0.32`+ and the error went away and it was compiling successfully during all changes in watch mode.
Thanks @jrburke for the repro with step-by-step directions!

As such, closing this as fixed. Please upgrade to `0.32`+ if you're experiencing this error.

**Comment by aaacafe786** [comment]
hey, i am using rollup with post css and lerna, it has not been fied in 0.32, please continue investigation i will help where i can

**Comment by agilgur5** [comment]
@aaacafe786 please file a new issue with a reproduction if you believe you're facing this. Just saying you're having this issue with little-to-no information is not helpful or productive. There is nothing to investigate without a reproduction.
That's like telling tech support "doesn't work on my computer" and nothing else -- there are no leads to follow up on... Not to mention, unlike tech support, maintainers are volunteers and not paid; please be respectful of volunteer maintainers' time.

What you're suggesting you're experiencing is also probably a different issue than the one mentioned here, given that the reproduction here no longer has this issue -- the fix is _confirmed_.
