### ISSUE TITLE
compatibility with rollup 2.0?

### ISSUE THREAD

**Issue by mesqueeb** [ezolenko/rollup-plugin-typescript2#215]
Hi!
I use this plugin in all my packages. Thanks a lot! I saw that Rollup 2.0 is released. But I'm scared to upgrade in case it will break this plugin.
Is it compatible?
Thanks a lot!!!

**Comment by ezolenko** [comment]
From what I can tell, rollup 2.0 should work. Plugin can build itself (after a type fix because rollup renamed something).

So you should be to use rollup 2. When switching, commit your output into source control (or same it on the side), then switch only rollup and build again, then diff the output. If it is the same (or changes make sense), you should be fine.
