### ISSUE TITLE
Is fs-extra 7.0.1 compatible?

### ISSUE THREAD

**Issue by dilyanpalauzov** [ezolenko/rollup-plugin-typescript2#220]
Your package.json contains `"dependencies": {"fs-extra": "8.1.0"}` while https://github.com/RJHwang/rollup-plugin-css-porter/blob/master/package.json contains `"dependencies": {"fs-extra": "^7.0.1"}`.  In turn on my system two fs-extras are installed: v7 and v8.

Please verify whether rollup-plugin-typescript can work with fs-extra 7.0.1 and if it can, add it under  "7.0.1 - 8" as peer dependency, so that I can have just one fs-extra.

**Comment by dilyanpalauzov** [comment]
See also https://github.com/RJHwang/rollup-plugin-css-porter/issues/5.

**Comment by ezolenko** [comment]
It is probably compatible, if it is not you should notice right away. It is better if the other plugin updates their dependencies instead of this one going backwards.

You could also use npm-shrinkwrap to force either one to the single version: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

**Comment by dilyanpalauzov** [comment]
Yes, other packages shall update their dependencies.
