### ISSUE TITLE
`Property 'xxx' does not exist on type 'Vue'` thrown when accessing public member of a Vue class (using `rollup-plugin-vue`)

### ISSUE THREAD

**Issue by olivierr91** [ezolenko/rollup-plugin-typescript2#235]
Not sure if this is a rollup-plugin-vue or a rollup-plugin-typescript2 issue. When calling a public method on a Vue/TypeScript class, an error `Property 'xxx' does not exist on type 'Vue'` is thrown.

Reproduction link
https://repl.it/@orobert91/PropertyDoesNotExistOnTypeVue

Steps to reproduce
Run the Replit.

What is expected?
To compile correctly. This code compiles fine with tsc and WebPack.

What is actually happening?
It does not compile.

**Comment by shukob** [comment]
Same here.
In my case
- BaseView extends Vue
- ChildView extends BaseView

Then call like `this.baseViewMethod()` within ChildView instance throws 
```
 TS2339: Property 'baseViewMethod' does not exist on type 'ChildView'.
```
on `rollup`.

**Comment by jzz4012650** [comment]
Same here.

**Comment by ezolenko** [comment]
This might be related: https://github.com/vuejs/rollup-plugin-vue/issues/311

**Comment by CdTgr** [comment]
Did anyone get a resolution for this?

**Comment by agilgur5** [comment]
`rollup-plugin-vue` is now archived/deprecated and per the linked issue, this looked like more of an issue there than here.

As such, and since this issue has not seen any activity in some time, will close this out as stale. 

Can re-open down the line if necessary, but I expect it won't be due to the status of `rollup-plugin-vue`
