### ISSUE TITLE
Problem with `target` field -- incorrect `tsconfig` usage

### ISSUE THREAD

**Issue by swelet** [ezolenko/rollup-plugin-typescript2#236]
I'm having the same problem as @yangwao https://github.com/ezolenko/rollup-plugin-typescript2/issues/217#issuecomment-601112772_ with the target field. I'm trying to write a class with a "get" accessor, and the compiler is giving me

`semantic error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.`

<img width="1387" alt="Screenshot 2020-07-28 at 12 37 58" src="https://user-images.githubusercontent.com/5476077/88655518-2c675a80-d0cf-11ea-9504-53e76da039a2.png">

eventhough target is allready es5.

<img width="531" alt="Screenshot 2020-07-28 at 12 38 59" src="https://user-images.githubusercontent.com/5476077/88655637-51f46400-d0cf-11ea-8bd6-4c6f909afd1e.png">

**Comment by ezolenko** [comment]
Works for me if I set target to es5 and use this code in a random class:

```    private _name : string = '[Animal]';
    get name():string{
        return this._name;
    }

    set name(name:string){
        this._name = name;
    }
```

**Comment by ezolenko** [comment]
Could you add verbose output? Part of it is a dump of parsed tsconfig.

**Comment by agilgur5** [comment]
OP seemed to have this as part of their Rollup config (as a screenshot instead of text unfortunately):

```js
 typescript({
  lib: ["es5", "es6", "es7", "dom"],
  target: "es5",
  declaration: true
})
```

While it's difficult to tell without a full `rollup.config.js` or a full `tsconfig.json` (and OP did not respond to requests for more information), that seems like incorrect usage of rpt2 to me.
rpt2 doesn't support those fields, those are fields of `tsconfig.json`'s `compilerOptions`. Can see rpt2's list of options in the docs [here](https://github.com/ezolenko/rollup-plugin-typescript2#plugin-options)
