### ISSUE TITLE
Question: What is the point of the 'typescript' option?

### ISSUE THREAD

**Issue by brandon-leapyear** [ezolenko/rollup-plugin-typescript2#252]
This says that if the option isn't set, the plugin will automatically set it to `require('typescript')`.

https://github.com/ezolenko/rollup-plugin-typescript2/blob/5ce7676ad0451df81e61190d42694f97085111fc/src/index.ts#L72-L74

I'm wondering why you would ever want to manually set the `typescript` option to `require('typescript')` then. Wouldn't calling `require('typescript')` in `rollup.config.js` always give the same answer as `require('typescript')` in the plugin?

**Comment by ezolenko** [comment]
You might want to use multiple versions of typescript for example, or have it in a non-standard place.

**Comment by brandon-leapyear** [comment]
I see. But the docs say

> When typescript version installed by the plugin (latest 2.x) is unacceptable, you can import your own typescript module and pass it in as typescript: require("typescript"). Must be 2.0+, things might break if transpiler interfaces changed enough from what the plugin was built against.

You would never literally do `typescript: require("typescript")`, you'd do `typescript: require("path/to/other/typescript")`, right? I'm mostly asking about a docs change, here

**Comment by ezolenko** [comment]
Yeah, `typescript: require("typescript")` is redundant -- the plugin will do that on its own if you don't provide `typescript` option. I'll change the doc.

**Comment by agilgur5** [comment]
Worth noting, `require('typescript')` from within rpt2 (vs. from within your `rollup.config.js`) actually _could_ resolve to something different [depending on how your `node_modules` ends up being laid out](https://nodejs.org/api/modules.html#loading-from-node_modules-folders).

For example, if it somehow ended up like this:

```
my-project
│   README.md
│   rollup.config.js
│
└───node_modules
│   │
│   └───typescript
│   │
│   └───rollup-plugin-typescript2
│       │   
|       └───node_modules
│           │   
|           └───typescript
```

You'd have two different TS versions depending on where `require('typescript')` was called.

Realistically, that shouldn't really happen unless `node_modules` is an erroneous state (e.g. need to run `npm dedupe` etc) since rpt2 sets TS as a peerDep, but it is something to be aware of in the Node ecosystem.

**Comment by agilgur5** [comment]
You can also use this for alternative TS implementations, such as [`ttypescript`](https://github.com/cevek/ttypescript), for instance for the purpose of #201 or something else.
