### ISSUE TITLE
Wrong compile result

### ISSUE THREAD

**Issue by Mister-Hope** [ezolenko/rollup-plugin-typescript2#262]
#### What happens and why it is wrong

![image](https://user-images.githubusercontent.com/33315834/107000399-c87ec680-67c2-11eb-9006-2e89143712c9.png)

I ran into a werid result, as you can see the

```js
const T = COMMENT_OPTIONS,
  V = PAGE_INFO_I18N;
VALINE_I18N;
```

is absolutly wrong, and will return an error `Uncaught SyntaxError: Unexpected token ':'` after `VALINE_I18N` replace by an object.

The project is working good for the past week, when it suddenly ran into this issue.

At a glance, I regard this as a `temp` error, but this issue still happens after I:

- delete `node_modules/.temp`

- delete the whole `node_modules/`

I am not sure if it is a bug (it probably not), but is there other temp or cache I missed? 

---

Sorry for not providing the config, but I think for this question it's not needed. And won't help.

**Comment by ezolenko** [comment]
If you think this is a cache error, try running with `clean: true`, although deleting node_modules should have killed the cache in node_modules\.cache\rollup-plugin-typescript2, unless you have it elsewhere?

**Comment by agilgur5** [comment]
So I've never seen an issue like this and can't reproduce this. Without a reproduction this is impossible to investigate unfortunately.

ezolenko's previous comment is accurate about the cache, so this is likely not a cache issue unless you changed the location of the cache by configuring rpt2. But you didn't provide a config, so can't tell if you did that either.

The compilation is done entirely by the TS `LanguageService` under-the-hood, so rpt2 has no impact on the output _syntax_ (we have _some_ control over things like resolution, but not _syntax_), that is entirely controlled by TS itself.

Given that this randomly occurred to OP after it was working for a week and then OP never responded and closed this without comment, I'm guessing it "solved itself". I.e. the problem was likely something in the environment, and not a bug in rpt2.

**Comment by Mister-Hope** [comment]
It's been a long time. I can tell that the original one is that:

```ts
// define.ts
decalre const CONST_A: xxx;
decalre const CONST_B: xxx;
decalre const CONST_C: xxx;

export const a = CONST_A;
export const b = CONST_B;
export const c = CONST_C;
```

```ts
// module.ts
import { a, b, c} from './define';

// a treeshakable thing. e.g: function
const func = ()=> a;

// real reference with b and c
// ...
```

I am not sure about the real content in `module.ts`, but at that time it's not a  cache error. lead to the above result.

I finally mananged to find a workaround (instead of fixing it at that time.)

**Comment by agilgur5** [comment]
> It seems that rollup mark `CONST_A` with side effect because it does not know what's it's value and preserve it

Hmm yea, it could potentially be a global with a getter that could cause a side-effect. Should be able to change Rollup's [`treeshake`](https://rollupjs.org/guide/en/#treeshake) property to make more assumptions to optimize and additionally treeshake that out.

`declare const` is basically meant [for globals](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#global-variables) so that makes sense that it could lead to treeshaking issues as globals basically _are_ side-effects.

Thanks for explaining the scenario! Should be helpful for future readers too who stumble upon this
