### ISSUE TITLE
`Failed to transpile` `tslib.es6.js` after update to `v0.30.0`

### ISSUE THREAD

**Issue by rafgraph** [ezolenko/rollup-plugin-typescript2#264]
#### What happens and why it is wrong
`failed to transpile '[...]/node_modules/tslib/tslib.es6.js'`

`rollup-plugin-typescript2` v0.29.0 works fine, v0.30.0 introduces this error.

The setup is a bit complex because it happened as part of [Rollpkg](https://github.com/rafgraph/rollpkg). It happens when tsconfig `target: es5` (so tslib is needed). I was alerted to it from this [issue](https://github.com/rafgraph/rollpkg/issues/5). Rollpkg [`v0.5.0`](https://github.com/rafgraph/rollpkg/tree/v0.5.0) has the bug, [`v0.5.1`](https://github.com/rafgraph/rollpkg/tree/v0.5.1) fixes it by downgrading `rollup-plugin-typescript2` to v0.29.0.

I'm using TypeScript `v4.2.3`.

**Comment by rafgraph** [comment]
You can reproduce it in this repo branch (it uses Rollpkg v0.5.0): https://github.com/rafgraph/react-router-hash-link/tree/rollpkg-0.5.0, just run `npm i && npm run build` to see the error. The main branch is fixed and uses Rollpkg v0.5.1.

**Comment by ezolenko** [comment]
I get this error when trying to do npm run build on that branch: 
```> rollpkg build

✓ Cleaning dist folder 7 ms
✓ Checking rollpkg invariants 3 ms
✓ Creating rollup config 0 ms
✓ Creating esm, cjs builds 815 ms
✓ Writing esm, cjs builds 217 ms
✓ ROLLPKG BUILD SUCCESS 😁😘 0 ms
✗ FAILED AT: Calculating Bundlephobia stats 

Bundlephobia Error: InstallError ```

Is this before rollup-plugin-typescript2 error?

**Comment by rafgraph** [comment]
Thanks for looking into this issue. The error is before this. I just created a fresh clone and install and got the error.

`node v14.15.4`
`npm v7.6.3`

```
react-router-hash-link on  remotes/origin/rollpkg-0.5.0 is 📦 v2.4.0 via ⬢ v14.15.4 took 12s
➜ npm run build

> react-router-hash-link@2.4.0 build
> rollpkg build

✓ Cleaning dist folder 1 ms
✓ Checking rollpkg invariants 3 ms
✓ Creating rollup config 0 ms
✗ FAILED AT: Creating esm, cjs builds

TypeScript Error: failed to transpile '/Users/rafael/dev/react-router-hash-link/node_modules/tslib/tslib.es6.js'
```

**Comment by ezolenko** [comment]
Yeah 
```
git branch
  main
* rollpkg-0.5.0
```

`node v14.16.0`
`npm 6.14.11`

I'm on windows if that makes a difference.

**Comment by rafgraph** [comment]
That could be it. I'm on a Mac v11.2.3. I upgraded to node 14.16 and set verbosity to 3. Here's the log:

```
➜ npm run build      

> react-router-hash-link@2.4.0 build
> rollpkg build

✓ Cleaning dist folder 1 ms
✓ Checking rollpkg invariants 4 ms
✓ Creating rollup config 0 ms
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/placeholder",
    "moduleResolution": 2,
    "allowNonTsExtensions": true
}
rpt2: parsed tsconfig: {
    "options": {
        "target": 1,
        "module": 99,
        "moduleResolution": 2,
        "esModuleInterop": true,
        "allowJs": true,
        "jsx": 2,
        "noEmit": false,
        "skipLibCheck": true,
        "strict": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "forceConsistentCasingInFileNames": true,
        "types": [],
        "declaration": false,
        "rootDir": "/Users/rafael/dev/react-router-hash-link/src",
        "sourceMap": true,
        "configFilePath": "/Users/rafael/dev/react-router-hash-link/tsconfig.json",
        "noEmitHelpers": false,
        "importHelpers": true,
        "noResolve": false,
        "inlineSourceMap": false,
        "outDir": "/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/placeholder",
        "allowNonTsExtensions": true
    },
    "fileNames": [
        "/Users/rafael/dev/react-router-hash-link/src/HashLink.jsx",
        "/Users/rafael/dev/react-router-hash-link/src/index.ts",
        "/Users/rafael/dev/react-router-hash-link/node_modules/rollpkg/configs/types/global.d.ts"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "compilerOptions": {
            "target": "ES5",
            "types": [],
            "declaration": false,
            "rootDir": "./src",
            "module": "ESNext",
            "sourceMap": true
        },
        "include": [
            "src",
            "./node_modules/rollpkg/configs/types"
        ],
        "exclude": [
            "**/__tests__",
            "**/__mocks__",
            "**/__snapshots__",
            "**/*.test.*",
            "**/*.spec.*",
            "**/*.mock.*"
        ],
        "extends": "rollpkg/configs/tsconfig.json",
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {
        "/users/rafael/dev/react-router-hash-link/src": 1,
        "/users/rafael/dev/react-router-hash-link/node_modules/rollpkg/configs/types": 1
    },
    "compileOnSave": false
}
rpt2: typescript version: 4.2.3
rpt2: tslib version: 2.1.0
rpt2: rollup version: 2.42.1
rpt2: rollup-plugin-typescript2 version: 0.30.0
rpt2: plugin options:
{
    "verbosity": 3,
    "tsconfigDefaults": {
        "compilerOptions": {
            "target": "ES2018",
            "types": [],
            "declaration": true,
            "rootDir": "./src"
        },
        "include": [
            "src",
            "./node_modules/rollpkg/configs/types"
        ],
        "exclude": [
            "**/__tests__",
            "**/__mocks__",
            "**/__snapshots__",
            "**/*.test.*",
            "**/*.spec.*",
            "**/*.mock.*"
        ]
    },
    "tsconfigOverride": {
        "compilerOptions": {
            "module": "ESNext",
            "sourceMap": true
        }
    },
    "include": [
        "**/*.ts+(|x)",
        "**/*.js+(|x)"
    ],
    "check": true,
    "clean": false,
    "cacheRoot": "/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2",
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "useTsconfigDeclarationDir": false,
    "transformers": [],
    "objectHashIgnoreUnknownHack": false,
    "cwd": "/Users/rafael/dev/react-router-hash-link",
    "typescript": "version 4.2.3"
}
rpt2: rollup config:
{
    "external": [
        "prop-types",
        "react",
        "react-router-dom"
    ],
    "input": "/Users/rafael/dev/react-router-hash-link/src/index.ts",
    "treeshake": {
        "annotations": true,
        "moduleSideEffects": false,
        "propertyReadSideEffects": false,
        "tryCatchDeoptimization": false,
        "unknownGlobalSideEffects": false
    },
    "plugins": [
        {
            "name": "node-resolve"
        },
        {
            "name": "commonjs"
        },
        {
            "name": "json"
        },
        {
            "name": "rpt2"
        },
        {
            "name": "sourcemaps"
        },
        {
            "name": "replace"
        }
    ]
}
rpt2: tsconfig path: /Users/rafael/dev/react-router-hash-link/tsconfig.json
rpt2: included:
[
    "**/*.ts+(|x)",
    "**/*.js+(|x)"
]
rpt2: excluded:
[
    "*.d.ts",
    "**/*.d.ts"
]
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/placeholder",
    "moduleResolution": 2,
    "allowNonTsExtensions": true
}
rpt2: parsed tsconfig: {
    "options": {
        "target": 1,
        "module": 99,
        "moduleResolution": 2,
        "esModuleInterop": true,
        "allowJs": true,
        "jsx": 2,
        "noEmit": false,
        "skipLibCheck": true,
        "strict": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "forceConsistentCasingInFileNames": true,
        "types": [],
        "declaration": false,
        "rootDir": "/Users/rafael/dev/react-router-hash-link/src",
        "sourceMap": true,
        "configFilePath": "/Users/rafael/dev/react-router-hash-link/tsconfig.json",
        "noEmitHelpers": false,
        "importHelpers": true,
        "noResolve": false,
        "inlineSourceMap": false,
        "outDir": "/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/placeholder",
        "allowNonTsExtensions": true
    },
    "fileNames": [
        "/Users/rafael/dev/react-router-hash-link/src/HashLink.jsx",
        "/Users/rafael/dev/react-router-hash-link/src/index.ts",
        "/Users/rafael/dev/react-router-hash-link/node_modules/rollpkg/configs/types/global.d.ts"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "compilerOptions": {
            "target": "ES5",
            "types": [],
            "declaration": false,
            "rootDir": "./src",
            "module": "ESNext",
            "sourceMap": true
        },
        "include": [
            "src",
            "./node_modules/rollpkg/configs/types"
        ],
        "exclude": [
            "**/__tests__",
            "**/__mocks__",
            "**/__snapshots__",
            "**/*.test.*",
            "**/*.spec.*",
            "**/*.mock.*"
        ],
        "extends": "rollpkg/configs/tsconfig.json",
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {
        "/users/rafael/dev/react-router-hash-link/src": 1,
        "/users/rafael/dev/react-router-hash-link/node_modules/rollpkg/configs/types": 1
    },
    "compileOnSave": false
}
rpt2: typescript version: 4.2.3
rpt2: tslib version: 2.1.0
rpt2: rollup version: 2.42.1
rpt2: rollup-plugin-typescript2 version: 0.30.0
rpt2: plugin options:
{
    "verbosity": 3,
    "tsconfigDefaults": {
        "compilerOptions": {
            "target": "ES2018",
            "types": [],
            "declaration": true,
            "rootDir": "./src"
        },
        "include": [
            "src",
            "./node_modules/rollpkg/configs/types"
        ],
        "exclude": [
            "**/__tests__",
            "**/__mocks__",
            "**/__snapshots__",
            "**/*.test.*",
            "**/*.spec.*",
            "**/*.mock.*"
        ]
    },
    "tsconfigOverride": {
        "compilerOptions": {
            "module": "ESNext",
            "sourceMap": true
        }
    },
    "include": [
        "**/*.ts+(|x)",
        "**/*.js+(|x)"
    ],
    "check": true,
    "clean": false,
    "cacheRoot": "/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2",
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "useTsconfigDeclarationDir": false,
    "transformers": [],
    "objectHashIgnoreUnknownHack": false,
    "cwd": "/Users/rafael/dev/react-router-hash-link",
    "typescript": "version 4.2.3"
}
rpt2: rollup config:
{
    "external": [
        "prop-types",
        "react",
        "react-router-dom"
    ],
    "input": "/Users/rafael/dev/react-router-hash-link/src/index.ts",
    "treeshake": {
        "annotations": true,
        "moduleSideEffects": false,
        "propertyReadSideEffects": false,
        "tryCatchDeoptimization": false,
        "unknownGlobalSideEffects": false
    },
    "plugins": [
        {
            "name": "node-resolve"
        },
        {
            "name": "commonjs"
        },
        {
            "name": "json"
        },
        {
            "name": "rpt2"
        },
        {
            "name": "sourcemaps"
        },
        {
            "name": "replace"
        },
        {
            "name": "replace"
        }
    ]
}
rpt2: tsconfig path: /Users/rafael/dev/react-router-hash-link/tsconfig.json
rpt2: included:
[
    "**/*.ts+(|x)",
    "**/*.js+(|x)"
]
rpt2: excluded:
[
    "*.d.ts",
    "**/*.d.ts"
]
🌏 Creating esm, cjs builds
rpt2: Ambient types:
rpt2:     /Users/rafael/dev/react-router-hash-link/node_modules/rollpkg/configs/types/global.d.ts
rpt2: ambient types changed, redoing all semantic diagnostics
rpt2: transpiling '/Users/rafael/dev/react-router-hash-link/src/index.ts'
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/code/cache/f7f0c04e781e1e31e7fd9db39d406bedbdac1adf'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/syntacticDiagnostics/cache/f7f0c04e781e1e31e7fd9db39d406bedbdac1adf'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/semanticDiagnostics/cache/f7f0c04e781e1e31e7fd9db39d406bedbdac1adf'
rpt2:     cache miss
rpt2: transpiling '/Users/rafael/dev/react-router-hash-link/src/index.ts'
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/code/cache/f7f0c04e781e1e31e7fd9db39d406bedbdac1adf'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/syntacticDiagnostics/cache/f7f0c04e781e1e31e7fd9db39d406bedbdac1adf'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/semanticDiagnostics/cache/f7f0c04e781e1e31e7fd9db39d406bedbdac1adf'
rpt2:     cache miss
rpt2: dependency '/Users/rafael/dev/react-router-hash-link/src/HashLink.jsx'
rpt2:     imported by '/Users/rafael/dev/react-router-hash-link/src/index.ts'
rpt2: resolving './HashLink' imported by '/Users/rafael/dev/react-router-hash-link/src/index.ts'
rpt2:     to '/Users/rafael/dev/react-router-hash-link/src/HashLink.jsx'
rpt2: dependency '/Users/rafael/dev/react-router-hash-link/src/HashLink.jsx'
rpt2:     imported by '/Users/rafael/dev/react-router-hash-link/src/index.ts'
rpt2: resolving './HashLink' imported by '/Users/rafael/dev/react-router-hash-link/src/index.ts'
rpt2:     to '/Users/rafael/dev/react-router-hash-link/src/HashLink.jsx'
rpt2: transpiling '/Users/rafael/dev/react-router-hash-link/src/HashLink.jsx'
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/code/cache/5f9503964a437ea32f78aefb79766c47f2089ee4'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/syntacticDiagnostics/cache/5f9503964a437ea32f78aefb79766c47f2089ee4'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/semanticDiagnostics/cache/5f9503964a437ea32f78aefb79766c47f2089ee4'
🌍 Creating esm, cjs builds
rpt2: transpiling '/Users/rafael/dev/react-router-hash-link/src/HashLink.jsx'
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/code/cache/5f9503964a437ea32f78aefb79766c47f2089ee4'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/syntacticDiagnostics/cache/5f9503964a437ea32f78aefb79766c47f2089ee4'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/semanticDiagnostics/cache/5f9503964a437ea32f78aefb79766c47f2089ee4'
rpt2:     cache miss
rpt2: transpiling '/Users/rafael/dev/react-router-hash-link/node_modules/tslib/tslib.es6.js'
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/code/cache/00b643a8eda2397d9119fe625f93d1531d1a1616'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/syntacticDiagnostics/cache/00b643a8eda2397d9119fe625f93d1531d1a1616'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/semanticDiagnostics/cache/00b643a8eda2397d9119fe625f93d1531d1a1616'
rpt2:     cache miss
✗ FAILED AT: Creating esm, cjs builds 

TypeScript Error: failed to transpile '/Users/rafael/dev/react-router-hash-link/node_modules/tslib/tslib.es6.js' 

rpt2: transpiling '/Users/rafael/dev/react-router-hash-link/node_modules/tslib/tslib.es6.js'
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/code/cache/00b643a8eda2397d9119fe625f93d1531d1a1616'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/syntacticDiagnostics/cache/00b643a8eda2397d9119fe625f93d1531d1a1616'
rpt2:     cache miss
rpt2:     cache: '/Users/rafael/dev/react-router-hash-link/node_modules/.cache/rollup-plugin-typescript2/rpt2_41e39e1ba39f2217f8bc6fb36fef2cfc9e4eafcb/semanticDiagnostics/cache/00b643a8eda2397d9119fe625f93d1531d1a1616'
rpt2:     cache miss
rpt2: rolling caches
npm ERR! code 1
npm ERR! path /Users/rafael/dev/react-router-hash-link
npm ERR! command failed
npm ERR! command sh -c rollpkg build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rafael/.npm/_logs/2021-03-23T17_12_01_735Z-debug.log
```

**Comment by ezolenko** [comment]
Surprising that there are no other errors, just `failed to transpile`. Usually there are typescript errors (semantic or diagnostic) printed before that, which caused typescript language service to not emit output .

**Comment by agilgur5** [comment]
So, I took a look at this issue and this was a doozy to figure out, but eventually got to the root cause

## initial investigation

> The setup is a bit complex because it happened as part of [Rollpkg](https://github.com/rafgraph/rollpkg). It happens when tsconfig `target: es5` (so tslib is needed). I was alerted to it from this [issue](https://github.com/rafgraph/rollpkg/issues/5). Rollpkg [`v0.5.0`](https://github.com/rafgraph/rollpkg/tree/v0.5.0) has the bug, [`v0.5.1`](https://github.com/rafgraph/rollpkg/tree/v0.5.1) fixes it by downgrading `rollup-plugin-typescript2` to v0.29.0.

This took a decent bit more time & effort to investigate as this is not a minimal reproduction -- in general, minimal repro makes it significantly _easier_ to investigate any issue. Given that maintainers have severely limited time, making it as easy possible for them to investigate should be the goal.
The permalinks that you gave (and which are still available!) are still helpful that being said.

It so happens that I solo-maintained TSDX for ~1.5 years (that's how I originally became a contributor here), so reading through `rollpkg`'s code was measuredly simpler, as they have somewhat similar layouts

<details>
  <summary><b><i>Sidebar</i></b>: TSDX comparison flaws </summary>

(Also your [TSDX comparison](https://github.com/rafgraph/rollpkg#rollpkg-compared-to-tsdx) is flawed, as TSDX actually uses _both_ TypeScript ([via rpt2](https://github.com/jaredpalmer/tsdx/blob/995099fd1d60104bca9ba334f8cd8c0835122840/src/createRollupConfig.ts#L152)) _and_ Babel (basically: ts -> esnext -> preset-env), and, again, that's how I found myself here.

Otherwise, the comparison is more or less accurate. See https://github.com/jaredpalmer/tsdx/issues/634 and https://github.com/jaredpalmer/tsdx/issues/635 as the two main RFCs I was pushing to get out of the configuration and compatibility hell.
`size-limit` was (partly) intentional though, given the various [trade-offs I analyzed](https://github.com/jaredpalmer/tsdx/pull/705#issuecomment-664028088). One was that there's no reason that stats should be tied to the build or slow it down).

</details>

Anyway, there were two things that stood out to me initially:
1. The error is failing to transpile `tslib`, which, well, shouldn't be transpiled in the first place, for a number of reasons
    - For instance, it's in `node_modules` and should be an `external`
1. This only occurred after updating to `0.30.0`
    - As I've investigated in a number of different issues, the main change there was a _breaking_ dependency upgrade of `@rollup/pluginutils` to v4, which included https://github.com/rollup/plugins/pull/517
    - `pluginutils` is responsible for filtering, i.e. `include` and `exclude` in most Rollup plugins' options.
    - Can read https://github.com/ezolenko/rollup-plugin-typescript2/issues/216#issuecomment-1140024487 and linked comments for more details, but v4 removed the `process.cwd()` that was added in front of any glob patterns given to it
    - Which means that files outside of the project dir could now be `include`d without changing the default settings. So this change ended up _unintentionally_ solving lots of monorepo issues. And also caused this issue, as it means things like `node_modules` can also be `include`d by default.
    - This is most plugins' default too, and is normally not an issue. Especially as unbundled deps get listed out in `external`s, and because rpt2's default `include` only has TS files, which are not often present and not meant to be `import`'d from `node_modules`

You can probably see where I'm going from here, but therein lies the problem.

## root cause analysis

`rollpkg`'s `tsconfig` sets [`allowJs: true`](https://github.com/rafgraph/rollpkg/blob/4160e9699298361c757fd14768372fb1d0a887b3/configs/tsconfig.json#L7) and sets rpt2's `include` to [also process JS files](https://github.com/rafgraph/rollpkg/blob/4160e9699298361c757fd14768372fb1d0a887b3/src/rollupBuilds.ts#L104).

Notably, what's missing is a changed `exclude`. rpt2's docs do [point out](https://github.com/ezolenko/rollup-plugin-typescript2#some-options-need-additional-configuration-on-plugin-side) that you probably want to add `node_modules` to your `exclude` if you're setting `allowJs` and `include`ing JS files.

(Your [`external`](https://github.com/rafgraph/rollpkg/blob/d0f6d2fca1e280fe2a13791d652b3bf5f98e2bf6/src/rollupBuilds.ts#L303) configuration is also a bit problematic in that it'll miss submodule deps, similar to https://github.com/stevenbenisek/rollup-plugin-auto-external/issues/16. I [personally](https://github.com/agilgur5/ts-library-base/blob/fc6ced78eb95729026399ad0f286aa880deff23d/rollup.config.ts#L2) use [`rollup-plugin-node-externals`](https://github.com/Septh/rollup-plugin-node-externals/), which [doesn't have this issue](https://github.com/Septh/rollup-plugin-node-externals/blob/11a7b4454f57c76436e71ecead0cc59ab0cc3b80/src/index.ts#L106))

So, with that, the problem becomes a lot more straightforward. [`HashLink.jsx`](https://github.com/rafgraph/react-router-hash-link/blob/7c2c2c84f386e60ff0e794833d9e3c37216ef831/src/HashLink.jsx) gets processed by rpt2 (logged on [this line](https://github.com/ezolenko/rollup-plugin-typescript2/blob/67f1d86a965af1aeef5e75e54eff833325ccb185/src/index.ts#L199)) and it returns this code at the top of the file:

```js
import { __rest } from "tslib";
import React from "react";
import PropTypes from "prop-types";
import { Link, NavLink } from "react-router-dom";
```

Note, of course, the presence of `tslib`.

So when rpt2 gives this ESM code to Rollup, it parses it and tries to resolve, and if configured to do so, transform, all the imports.
Given the lack of `tslib` in your [deps](https://github.com/rafgraph/react-router-hash-link/blob/7c2c2c84f386e60ff0e794833d9e3c37216ef831/package.json#L37), this means that `rollpkg` doesn't add it to your `external`s list, meaning that `tslib` ends up getting processed by your Rollup plugins.
And, given the lack of `exclude`, that means rpt2 tries processing `tslib`.

So the solution therein is to add `tslib` to your deps. You probably also want to add `node_modules` to `rollpkg`'s `exclude`.

### what about the lacking error though?

> Surprising that there are no other errors, just `failed to transpile`. Usually there are typescript errors (semantic or diagnostic) printed before that, which caused typescript language service to not emit output .

I dug a bit more to really understand this though, in particular as the lack of syntactic or semantic errors is still pretty strange. This is where things start to get complicated... especially as we get into the lacking TS Compiler docs 😕 

The [`failed to transpile`](https://github.com/ezolenko/rollup-plugin-typescript2/blob/67f1d86a965af1aeef5e75e54eff833325ccb185/src/index.ts#L209) error message means that rpt2 hit what it currently considers a fatal error somewhere. This results in TS [skipping emit](https://github.com/ezolenko/rollup-plugin-typescript2/blob/67f1d86a965af1aeef5e75e54eff833325ccb185/src/index.ts#L201) of files.

_Normally_, this is caused either by a compiler option error (i.e. `tsconfig` configuration issue) or a syntactic or semantic error (i.e. type-checking issue). The fact that neither was printed out in this case is strange, and often indicative of a bug.

I did some logging and that did not make things any less confusing, unfortunately...

`emitSkipped` and no files, but `id` clearly exists:
```txt
rpt2: transpiling '/rpt2-issue-264/node_modules/tslib/tslib.es6.js'
{
  outputFiles: [],
  emitSkipped: true,
  diagnostics: [],
  exportedModulesFromDeclarationEmit: undefined
}
```

no semantic or syntactic errors (which is to be expected, given that this is compiled `tslib` helper code):
```txt
[]
[]
```

snapshot exists and is correct (matches the exact source code of `tslib.es6.js`):
```txt
StringScriptSnapshot {
  text: '/*! *****************************************************************************\r\n' +
    'Copyright (c) Microsoft Corporation.\r\n' +
    '....'
}
```

So that's odd. I've never seen `emitSkipped` in a scenario like this (and I don't think ezolenko has either).

### figuring out `emitSkipped`

So I decided to look into `emitSkipped` in more detail.

Unfortunately, as usual, the [TS Compiler API Docs](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API) don't elaborate in any way on this. It's just used in 2 examples there, and that's what most TS Compiler integrations base their implementation on, including rpt2. Based on that example, I didn't see anything strange about rpt2's usage (which I've already read through dozens of times too).

So I did some more searching about `emitSkipped`. I stumbled upon this issue in `ts-node`: https://github.com/TypeStrong/ts-node/issues/693 . That happened to get some explanatory comments on it literally [yesterday](https://github.com/TypeStrong/ts-node/issues/693#issuecomment-1166662842). Per that comment, it turns out this a `rootDir` issue.

From the [TSConfig Reference on `rootDir`](https://www.typescriptlang.org/tsconfig#rootDir):

> Note that TypeScript will never write an output file to a directory outside of [`outDir`](https://www.typescriptlang.org/tsconfig#outDir), and will never skip emitting a file. For this reason, `rootDir` also enforces that all files which need to be emitted are underneath the `rootDir` path.

So, it turns out (basically through reverse-engineering as the TS Compiler Docs don't remotely go into this), that a compiled file will have `emitSkipped` set when that file is outside of the `rootDir`

And indeed, `rollpkg` (similarly to TSDX), sets a [default `rootDir`](https://github.com/rafgraph/rollpkg/blob/2c5b371ced4a47205344479773c1778c026e4fd2/src/rollupBuilds.ts#L77) of `./src`.
`./node_modules/tslib/tslib.es6.js` is clearly outside of `./src` and so outside of your `rootDir` and hence its emit gets skipped.

But normally a `rootDir` issue will throw a compiler options error (c.f. https://github.com/jaredpalmer/tsdx/issues/638#issue-586338455), such as:

```
rpt2: options error TS6059: File '/project/test/testUtils.ts' is not under 'rootDir' '/project/src'. 'rootDir' is expected to contain all source files.
```

But it doesn't here.

Well that's because TS doesn't know what all the files are ahead-of-time.
`tsc` only reads the `tsconfig` `include` and bases it off that. But with Rollup and plugins, your files get transformed along the way.
In this case, the `tslib` import was added during compilation (wasn't there before) and then the lack of `external` and plugin `exclude` meant that `tslib` got passed to rpt2.
So the compiler, at run-time, is given a file outside of `rootDir` that it didn't know about beforehand. There's no compiler options error as this is after parsing the compiler opts and not expected based on the `tsconfig.json`. So the compiler just returns an empty file with `emitSkipped` .... which apparently can indicate that there's a previously undetected `rootDir` issue that isn't documented in the TS Compiler API docs.

Root cause found.

## next steps

For @rafgraph , the next steps are fairly straightforward, add `tslib` to deps in `react-router-hash-link`, and, ideally, `exclude` `node_modules` in `rollpkg`. Could also add `tslib` manually to `external`s in `rollpkg`. (maybe modify the TSDX comparison section too 😉 )

For rpt2, the next steps are more opaque. This is the only time this issue has occurred too, so it's pretty rare.

`ts-node` addressed this in an intriguing way in https://github.com/TypeStrong/ts-node/pull/1629 which implements https://github.com/TypeStrong/ts-node/issues/1345. Basically, when `emitSkipped`, `ts-node` will switch to the simpler [`transpileModule` API](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function), which just does TS -> JS with no type-checking (i.e. similar to Babel and `isolatedModules`).

I'm not sure if that is ideal behavior for rpt2 though, which does not have as general a use-case as `ts-node`.
rpt2 is _only_ meant to compile projects (not arbitrary code, which is one of `ts-node`'s capabilities and purposes) and so should respect `tsconfig.json` as much as possible within the constraints of Rollup semantics.

This does hit a Rollup boundary, but I think in this case, throwing a `rootDir` compiler options error would be the most accurate behavior and is closest to what `tsc` would do, which we try to follow to aim for the "principle of least surprise".

I wrote the text of the `rootDir` error above, which we could copy+paste, but ideally, we should pull that from the TS API somewhere, which would also make it more resilient to error code / error message changes.

The _one_ caveat is that given that `emitSkipped` is mostly undocumented, it's difficult to tell if there are other scenarios where `emitSkipped` would be hit but there are no syntactic or semantic errors.
(I also checked the TS [source code](https://github.com/microsoft/TypeScript/search?p=1&q=emitSkipped) references to `emitSkipped` and that did not help my understanding much... there's only a dozen or so references in the source though (not including tests etc), that being said).

So what we could do is, if `emitSkipped` and no diagnostics, check the `id` of the file currently being processed (i.e. its path) against the `rootDir`, which we have access to. If it's not within `rootDir`, we could conclude that it is indeed a `rootDir` issue, and throw the `rootDir` error. Basically re-implementing some simple TS logic.
Otherwise, we leave it as just `failed to transpile`, as it would therefore be an unknown error (as in, if it is none of syntactic, semantic, or `rootDir` error).

Low priority given the rarity of the issue and that this change just improves DX (it's not a bugfix in that sense, more a feature), but, that being said, it should be fairly simple to implement.
