### ISSUE TITLE
How to put types into a single folder? (instead of one per format)

### ISSUE THREAD

**Issue by Emiliano-Bucci** [ezolenko/rollup-plugin-typescript2#266]
Hi! Is there a way to generate a single types folder (let's say in the dist root folder) so users should import directly from the package name, instead of importing from the specific bundle folder (like /es, or /umd)?

I've tried different solutions (using `useTsConfigDeclarationDir: true`) but without any luck; types are still being generated in the specific bundle folder.

**Comment by ezolenko** [comment]
What declaration dir did you set in tsconfig?

**Comment by agilgur5** [comment]
Per above comment, I believe specifying `declarationDir` with `useTsconfigDeclarationDir` should achieve the requested behavior.

Otherwise, that sounds like it is outputting correctly, side-by-side with your output.

Closing due to that as well as stale as OP never responded to requests for more information.
