### ISSUE TITLE
tslib import issues in #12 are still rampant

### ISSUE THREAD

**Issue by IronSean** [ezolenko/rollup-plugin-typescript2#270]
https://github.com/ezolenko/rollup-plugin-typescript2/issues/12 is already closed but the regular and ongoing conversation shows the issues aren't resolved and adding direct dependencies for things that should be resolved automatically is still the best bandage solution propsed.

**Comment by ezolenko** [comment]
tslib 2.1.0 is already a direct dependency of rpt2, so it should work, unless you are using something not in 2.1.0?

**Comment by IronSean** [comment]
I think we tracked it down to being issues with npm 7, reverting to npm 6 and it's older dependency resolution approach seemed to fix things.

**Comment by agilgur5** [comment]
Closing this out as OP was able to resolve this themselves and it did not seem to be an issue with this plugin.
Much of the remaining discussions in #12 are very similar, where some dependency resolution isn't working and a fresh install or something else makes it work, so also marking as duplicate in that sense.
The original issue is also like ~5 years old and was resolved with `moduleResolution: 'node'` (vs. the legacy `classic` option), so I'm actually not sure that the further discussion is related to the original issue either.

Also, #293 unlocked the version of `tslib` in this plugin's `dependencies`, so that should help with any dependency resolution issues as well.
