### ISSUE TITLE
How can I generate typings compatible with an older version of TS?

### ISSUE THREAD

**Issue by leerle** [ezolenko/rollup-plugin-typescript2#281]
#### How can I escape the generated high version ts definition  into the low version available ts definition?

My component library is packaged using rollup and rollup-plugin-typescrupt2, using typescript 3.8, including the wording of export type {}. However, when used in a project of a lower typescript version, the new ts definition syntax cannot be recognized. How can I do it, transfer the high version in the ts definition packaged by rollup to the low version definition

**Comment by leerle** [comment]
before：
![image](https://user-images.githubusercontent.com/32125150/132685710-f57589bf-a016-4e24-8ac0-e5c5f5d0fef5.png)
after：
![image](https://user-images.githubusercontent.com/32125150/132685761-a401cf32-a70c-4bff-a88e-36ac784f770f.png)

I don't want this "type".

**Comment by ezolenko** [comment]
You can use your own version of typescript with this plugin, see `typescript` option in readme. Use the newest typescript version that generates compatible type definitions.

**Comment by agilgur5** [comment]
As far as I know, TS itself has no way of "downleveling" its own syntax ([`downlevelIteration`](https://www.typescriptlang.org/tsconfig#downlevelIteration) is only for ECMA iterables), so I don't believe what you're asking for is built-in to TS (let alone this plugin).

Per the [TS 3.8 blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports), the `export type` syntax was only added in TS 3.8.
If you want your typing to be compatible with older versions of TS, you'd have to use the regular `export` syntax and avoid using `export type`. That has its own caveats of course, which is why TS released it as a new feature.

There might be some other libraries that can "downcompile" your TS syntax to older TS syntax (in this case, removing `type` is actually pretty straightforward), but it is currently out-of-scope of this plugin.

**Comment by agilgur5** [comment]
> There might be some other libraries that can "downcompile" your TS syntax to older TS syntax (in this case, removing `type` is actually pretty straightforward), but it is currently out-of-scope of this plugin.

For reference, I did in fact find a library that does this: [`downlevel-dts`](https://github.com/sandersn/downlevel-dts).

Per its docs, there's lots of caveats that come with "downcompilation".

As it's a rare use-case and rpt2's goal is to be as close as possible to `tsc`, I'm not sure that would ever be internally supported by rpt2 either.
That being said, `downlevel-dts` could be made into a Rollup plugin and then chained with rpt2, which I think is better modularity / separation of concerns / Unix philosophy too. Similar to declaration bundling with `rollup-plugin-dts`
