### ISSUE TITLE
support sourcemap in vite dev mode

### ISSUE THREAD

**Issue by agileago** [ezolenko/rollup-plugin-typescript2#294]
#### Environment

as a vite plugin to develop 

##### Versions

latest

repo:  clone  https://github.com/agileago/vue3-oop
```
pnpm install
pnpm run dev
```

you will see `count.service.ts` sourcemap is not right and can't breakpoint . but when you change `vite.config.ts` to use `@rollup/plugin-typescript` . it is ok. because `@rollup/plugin-typescript` is too slow. by the way. because i use decorator so i need typescript compile not esbuild

**Comment by lake2** [comment]
same issue + 1

**Comment by agilgur5** [comment]
Since OP did not link a permalink, I had to find an [old `git` tag](https://github.com/agileago/vue3-oop/blob/6703b62dbe7510c47f1556703f6728e794512517/example/count.service.ts) myself in their repo to find the code. I also can't read the language it's written in (Chinese I assume? based on the alphabet and Vue's popularity there)

There's a confounding issue here with `pnpm` that may be the cause but it's hard to tell with a complicated repo like that. A minimal reproduction would be very helpful, see the [repro environment here](https://stackblitz.com/edit/rpt2-repro?file=src/index.ts).
If you were using any symlinks with `pnpm`, you may have hit #234. That was recently fixed in #332 and released in [`0.32.0`](https://github.com/ezolenko/rollup-plugin-typescript2/releases/0.32.0)
