### ISSUE TITLE
add prefix to error messages to improve DX

### ISSUE THREAD

**Issue by jackson-yyy** [ezolenko/rollup-plugin-typescript2#300]
https://github.com/ezolenko/rollup-plugin-typescript2/blob/4e9f8fff080072a90164590b399768ca21a4d4e0/src/parse-tsconfig.ts#L27

for this example, it could be like ```throw new Error(`rpt2: failed to read '${fileName}'`)```

if you allow, i can provide a pull request later, covering the whole project.

**Comment by ezolenko** [comment]
I added prefixes in master, let me know if I missed any

**Comment by agilgur5** [comment]
Released in [0.32.0](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.32.0)

**Comment by agilgur5** [comment]
> let me know if I missed any

Got the remaining few in #382 .

Also, for other readers, per that PR, the vast majority of errors were already auto-prefixed by [`RollupContext`](https://github.com/ezolenko/rollup-plugin-typescript2/blob/61d78bd2f3fcf2ad5707086f152bc6c93e6d0715/src/rollupcontext.ts#L8) and [`ConsoleContext`](https://github.com/ezolenko/rollup-plugin-typescript2/blob/61d78bd2f3fcf2ad5707086f152bc6c93e6d0715/src/context.ts#L22).
Only a handful of errors were thrown in the [`options`](https://rollupjs.org/guide/en/#options) hook, which does not implement Rollup's `this.error`, and so some prefixes were missing since they do not go through the above logging wrappers.
