### ISSUE TITLE
Could the project please publish a changelog?

### ISSUE THREAD

**Issue by ThisIsMissEm** [ezolenko/rollup-plugin-typescript2#418]
Hi! Would it be possible to get a `CHANGELOG.md` file publish or releases on github setup?

Currently when you release a new version, the only thing I can look at is the commits for changes, which are often far too involved for users of your package to understand. That and the semver version, but that relies on you strictly adhering to semver, which generally isn't the case in the npm ecosystem from what I've seen.

This would make upgrading versions much easier for downstream developers to approach; right now I just have to hope the update doesn't break anything.

**Comment by agilgur5** [comment]
### Release Notes

> releases on github setup?

Have you seen the [past](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.32.0) [3](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.32.1) [releases](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.33.0.1) on GitHub?

I wrote up those 3 as I was added as a maintainer [a few months ago](https://github.com/ezolenko/rollup-plugin-typescript2/pull/311#issuecomment-1106646015) after being a long-time contributor. I've made significant improvements to the [codebase](https://github.com/ezolenko/rollup-plugin-typescript2/pulls?q=author%3Aagilgur5+), [issues](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=is%3Aissue+involves%3Aagilgur5), [labels](https://github.com/ezolenko/rollup-plugin-typescript2/labels), [templates](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=author%3Aagilgur5+label%3A%22scope%3A+github%22+), [testing](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=author%3Aagilgur5+label%3A%22scope%3A+tests%22+), etc, including improving the release notes (as linked above) by adding highlights, descriptions, links, summaries, etc. (The past few releases also include significantly more changes than before due to my involvement, so spoiler tags etc have also been added).

These should be much better than the [previous](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.28.0) [release notes](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.27.3) as such. I don't have publishing permissions though, so I write/edit them up async after ezolenko publishes a release currently.
Otherwise, I can relate to your concern about the lack of changelogs in the past, as when I was just a user/contributor, I myself had [previously clamored about it](https://github.com/jaredpalmer/tsdx/pull/896#issuecomment-704698148) as well and read through diffs to see the changes.

If you'd still like to see more improvements to the release notes than those already done, please let me know what kind of specific stylistic changes you think would be helpful in particular, always open to improving the craft! (in my experience as a maintainer of multiple libraries, release notes are "more of an art form than a science" 😅 and can vary widely between types of libraries as well each individual release depending on the changes therein)

### Dependabot

I noticed from your contribution history that some of the repos you maintain use Dependabot, and in [some PRs](https://github.com/inrupt/solid-client-access-grants-js/pull/271), Dependabot did include the detailed notes from GitHub Releases. Though it looks like it [missed them](https://github.com/inrupt/solid-client-access-grants-js/pull/327) in the last version bump.
That might be because, per [`0.33.0`'s release notes](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.33.0.1), of a tagging mistake ezolenko accidentally made this release. That's the only time that's happened and I don't think either of us knew it would impact Dependabot PRs as such, so apologies on the inconvenience.
Rest assured though, that the [GitHub Releases page](https://github.com/ezolenko/rollup-plugin-typescript2/releases) has always had some form of release notes (though an edited version might be a bit delayed, per my note above).

### `CHANGELOG.md`

> Would it be possible to get a `CHANGELOG.md` file

I actually just realized that there is no `CHANGELOG.md` in this repo. I normally have [a simple one](https://github.com/agilgur5/react-signature-canvas/blob/64c7c4989cb6dceb8ac92e03d43070b8ff5d1043/CHANGELOG.md) in my libraries that just points to the release notes on GH Releases for clarity / less confusion, but I guess I never noticed or added one since becoming a maintainer here. Thanks for pointing that out, I'll add a similar one shortly! 🙂 

### SemVer

> That and the semver version, but that relies on you strictly adhering to semver, which generally isn't the case in the npm ecosystem from what I've seen.

Just for reference, historically, ezolenko is very conservative with versioning, preferring releasing a minor over patch change (and since rpt2 is still in `0.x`, minors can be breaking) when there's a possibility for breakage. Can see an example of that in our discussion about [the numbering for the latest release](https://github.com/ezolenko/rollup-plugin-typescript2/pull/410#issuecomment-1221106609).

Personally, I'd also disagree with the characterization that generally the NPM ecosystem doesn't adhere to SemVer, as I think it does so better than any other package manager ecosystem I've worked with (IMO). Alternative versioning schemes, like [ComVer](https://gitlab.com/staltz/comver), that try to improve on the subjectivity SemVer, were also largely born out of the JS/TS ecosystem. But that's neither here nor there.

TypeScript is also a bit of sub-ecosystem and this seems to be not that well-known in the TS ecosystem, so wanted to note here just in case: TS itself [does not strictly follow SemVer](https://github.com/microsoft/TypeScript/issues/14116), as that can be very difficult with a type-checker (e.g. a feature of that adds a type-error will break existing users), among other reasons. So downstream packages may be impacted by that too.
