### ISSUE TITLE
`Error: Unexpected early exit`

### ISSUE THREAD

**Issue by tjx666** [ezolenko/rollup-plugin-typescript2#430]
## Troubleshooting

1. Does `tsc` have the same output? If so, please explain why this is incorrect behavior
   
   tsc no error:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/41773861/205738329-aa85cd5b-4f5a-40b0-bd3a-be75ab83fb37.png">

   but this plugin:

   
<img width="945" alt="image" src="https://user-images.githubusercontent.com/41773861/205738414-bbef3fef-ba7f-4c8a-bff4-b1a9384bc460.png">

1. Does your Rollup plugin order match [this plugin's compatibility](https://github.com/ezolenko/rollup-plugin-typescript2#compatibility)? If not, please elaborate
  Yes

1. Can you create a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this behavior? Preferably, use [this environment](https://stackblitz.com/edit/rpt2-repro) for your reproduction

  This is my company project, maybe later

## What happens and why it is incorrect

throw error
<img width="922" alt="image" src="https://user-images.githubusercontent.com/41773861/205741328-ab21db96-e050-4f85-aa52-01fd003dd365.png">

### Versions

<img width="712" alt="image" src="https://user-images.githubusercontent.com/41773861/205741439-f609642c-a2f5-4273-96b6-639d7e728fc4.png">

<details>
  <summary><h4><code>rollup.config.js</code></h4>: </summary>

<img width="846" alt="image" src="https://user-images.githubusercontent.com/41773861/205741599-58592a94-472a-4e3c-94ed-4d5a2e9672e7.png">

</details>

<details>
  <summary><h4><code>tsconfig.json</code></h4>: </summary>

```json5
{
    "$schema": "https://json.schemastore.org/tsconfig",
    "display": "Base",
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "lib": ["DOM", "ESNext"],
        "composite": false,
        "declaration": false,
        "esModuleInterop": true,
        "jsx": "preserve",
        "allowJs": true,
        "strictFunctionTypes": false,
        "allowSyntheticDefaultImports": true,
        "forceConsistentCasingInFileNames": true,
        "inlineSources": false,
        "isolatedModules": true,
        "moduleResolution": "node",
        "noUnusedParameters": false,
        "preserveWatchOutput": true,
        "skipLibCheck": true,
        "strict": true,
        "resolveJsonModule": true,
        "removeComments": true,
        "noUnusedLocals": false,
        "noImplicitAny": false,
        "noImplicitThis": true,
        "experimentalDecorators": true,
        "types": ["@scripts/types/global"]
    },
    "vueCompilerOptions": {
        "target": 2.7
    }
}
```

</details>

<details>
  <summary><h4><code>package.json</code></h4>: </summary>

```json

```

</details>

<details>
  <summary><h4>plugin output with verbosity 3</h4>: </summary>

```text

```

</details>

**Comment by tjx666** [comment]
even doesn't work when I add `// @ts-no-check` comment

**Comment by agilgur5** [comment]
## parsing error

> even doesn't work when I add `// @ts-no-check` comment

So this looks to be a plugin parsing error and unrelated to type-checking.

The error is:
```
[!] Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(rpt2) transform "<filepath>.ts"
```

The only reference online I can find for this error is to Vite: https://github.com/vitejs/vite/issues/8479. This seems to be a recent error in Rollup, so I wonder if this is due to a newer version of Rollup that we haven't tested with.

The message and that issue suggests it's either an unresolved Promise somewhere or a deadlock or something. That would be a potential regression from #406 (which added asynchronous transforms in order to pipe elided  TS imports into Rollup).

### workarounds

As such two possible workarounds would be:
1. downgrade Rollup
2. downgrade rpt2 to < `0.34.0`, pre #406.

## needs more information and repro in order to fix

While this seems to be related to the code in #406, that was extensively tested and hasn't had any bug reports in a few months. I also added deadlock prevention with cycle checking there.

So it's really difficult to tell what the problematic code is without more information.

A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) could help quite a bit to narrow down the issue and run this in a debugger.

You seem to have quite a bit of dependencies here (and not all are listed) which makes it difficult to narrow down. The `verbosity: 3` log also doesn't seem complete -- with a full log we might be able to see if there's a cycle or something.

### text > screenshots

Please note that text is [strongly preferred](https://meta.stackoverflow.com/q/303812/3431180) over screenshots when reporting GitHub issues (or StackOverflow questions, per the link), as text can be copied, searched, etc and is significantly more accessible, while screenshots cannot / are not nearly as accessible.

**Comment by agilgur5** [comment]
Closing as stale as there has been no response for over a month now and there is no way to move forward without more information from OP.
