### ISSUE TITLE
Retrieve plugin config from rollup config file?

### ISSUE THREAD

**Issue by YonatanKra** [ezolenko/rollup-plugin-typescript2#461]
I'm using a 3rd party library that generates the config for me like this:
```js
module.exports = function setVividRollupConfig(config) {
   const rpt2 = config.plugins.find(plugin => plugin.name === 'rpt2');
}
```
I want to use the plugin, but change only one option.
Do I need to recreate the plugin? Or is there a way to change only one property in the configuration?
Thanks!

**Comment by agilgur5** [comment]
This is a question for the library you mention or Rollup, not rpt2 as it is not specific to rpt2 (this question applies to _any_ plugin or configuration)

That being said, having maintained a wrapper library in the past (I was the longest solo maintainer of TSDX), I can tell you the answer to that is no.
Plugins are functions and plugin config is a function argument. You cannot retrieve an argument of a function from outside of it or without a reference.
As such, if you are the maintainer of such a wrapper library and allow such overrides, it may make sense to export each plugin's config so that users can do plugin config merging.
