### ISSUE TITLE
using it with rollup-plugin-alias

### ISSUE THREAD

**Issue by lilijialiang** [ezolenko/rollup-plugin-typescript2#65]
#### Environment 

node v8.9.1

#### Versions
- typescript: 2.7.2
- rollup: 0.56.5
- rollup-plugin-typescript2: 0.12.0

#### rollup.config.js

```js
const path = require('path');

import typescript from 'rollup-plugin-typescript2';
import alias from 'rollup-plugin-alias';

export default {
    input: './src/index.ts',
    output: {
        file: 'build.js',
        format: 'umd',
        name: 'build',
    },
    plugins: [
        typescript( ),
        alias( {
            core: path.resolve( __dirname, './src/core' ),
        } ),
    ],
};
```

#### tsconfig.json

```json
{
    "compilerOptions": {
        "target": "es2015"
    }
}
```

#### package.json

```json
{
  "name": "rollup-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "rollup -c ./rollup.config.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "rollup": "^0.56.5",
    "rollup-plugin-alias": "^1.4.0",
    "rollup-plugin-typescript2": "^0.12.0",
    "typescript": "^2.7.2"
  }
}
```
#### TS files

```js
// ./src/index.ts
import A from 'core/a';
export { A };
```

```js
// ./src/core/a.ts
export default function  () {
    const x = 12;
    console.log( x );
};
```

#### Error

```
rollup-demo/src/index.ts(1,15): semantic error TS2307 Cannot find module 'core/a'.
```

#### Problem

If use `rollup-plugin-alias` alone, it will work. 

but with `rollup-plugin-typescript2` used together, it can't find the module

**Comment by ezolenko** [comment]
Did you try placing alias() in front of typescript()?

Can you work around this by using `baseUrl` in tsconfig?

See more info here:
https://decembersoft.com/posts/say-goodbye-to-relative-paths-in-typescript-imports/

**Comment by ezolenko** [comment]
Likely plugin order thing

**Comment by viT-1** [comment]
I tried this configuration. Set alias in front of typescript2 not helped =(

**Comment by alsotang** [comment]
I met the same problem when using `@rollup/plugin-alias` and `@rollup/plugin-typescript`. 
Moving `alias` bebind `typescript` solve the problem.

**Comment by agilgur5** [comment]
> I tried this configuration. Set alias in front of typescript2 not helped =(

Looking at the original config, I believe it's because it didn't set a `.ts` extension in the [`alias` `resolve` options](https://github.com/rollup/plugins/tree/544702c84d946477eab2b501eed8c52c4222ce93/packages/alias#resolve). Notably, https://github.com/ezolenko/rollup-plugin-typescript2/issues/125#issue-391855582 sets it and got it to work.
The [current version](https://github.com/rollup/plugins/tree/master/packages/alias) of `alias` has different options, but a similar configuration is probably needed for it.

<hr>

....That being said, once you fix the extensions, you may end up missing the aliases in your declaration files, i.e. #125 .
Per [my comment there](https://github.com/ezolenko/rollup-plugin-typescript2/issues/125#issuecomment-1125549726), please see #201 for further discussion, workarounds, etc
